import { spawn } from 'child_process';
import { closeSync, mkdtempSync, openSync, readFileSync, writeFileSync } from 'fs';
import { tmpdir } from 'os';
import { join } from 'path';
import { buildContinuationPrompt, buildInitPrompt, buildObservationPrompt, buildSummaryPrompt } from '../../sdk/prompts.js';
import { SettingsDefaultsManager } from '../../shared/SettingsDefaultsManager.js';
import { USER_SETTINGS_PATH } from '../../shared/paths.js';
import { logger } from '../../utils/logger.js';
import { ModeManager } from '../domain/ModeManager.js';
import type { ModeConfig } from '../domain/types.js';
import type { ActiveSession, ConversationMessage, PendingMessageWithId } from '../worker-types.js';
import { DatabaseManager } from './DatabaseManager.js';
import { SessionManager } from './SessionManager.js';
import { isAbortError, processAgentResponse, type WorkerRef } from './agents/index.js';
import { ClassifiedProviderError } from './provider-errors.js';

const DEFAULT_TIMEOUT_MS = 120_000;
const DEFAULT_MAX_CONTEXT_MESSAGES = 20;
const DEFAULT_MAX_ESTIMATED_TOKENS = 100_000;
const CHARS_PER_TOKEN_ESTIMATE = 4;

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'"'"'`)}'`;
}

function textFromUnknown(value: unknown): string {
  if (typeof value === 'string') return value;
  if (Array.isArray(value)) return value.map(textFromUnknown).filter(Boolean).join('\n');
  if (value && typeof value === 'object') {
    const record = value as Record<string, unknown>;
    if (typeof record.text === 'string') return record.text;
    if (typeof record.content === 'string') return record.content;
    return textFromUnknown(record.content ?? record.message ?? record.result ?? record.value);
  }
  return '';
}

function extractAssistantTextFromJsonEvents(stdout: string): string {
  const finalChunks: string[] = [];
  const deltaChunks: string[] = [];
  for (const line of stdout.split(/\r?\n/)) {
    if (!line.trim()) continue;
    try {
      const event = JSON.parse(line) as Record<string, any>;
      if (event.type === 'message_update' && event.assistantMessageEvent?.type === 'text_delta') {
        const delta = textFromUnknown(event.assistantMessageEvent.delta);
        if (delta) deltaChunks.push(delta);
      } else if (event.type === 'message_end' && event.message?.role === 'assistant') {
        const text = textFromUnknown(event.message.content).trim();
        if (text) finalChunks.push(text);
      } else if (event.type === 'message_update' && event.assistantMessageEvent?.type === 'text_end') {
        const text = textFromUnknown(event.assistantMessageEvent.content).trim();
        if (text) finalChunks.push(text);
      }
    } catch {
      // Ignore non-JSON lines.
    }
  }
  return (finalChunks.join('\n').trim() || deltaChunks.join('').trim());
}

function buildPiPrompt(history: ConversationMessage[]): string {
  return history
    .map((message) => `## ${message.role}\n${message.content}`)
    .join('\n\n---\n\n');
}

function buildPiSystemPrompt(): string {
  return `You are claude-mem's background fact extraction agent.

You receive synthetic prompts generated by claude-mem for session init, tool observations, and session summaries. Follow those prompts exactly and produce the structured memory/summary response requested by the prompt. Do not use tools. Do not ask questions. Return only the requested content for claude-mem to parse.`;
}

export class PiProvider {
  constructor(
    private dbManager: DatabaseManager,
    private sessionManager: SessionManager,
  ) {}

  async startSession(session: ActiveSession, worker?: WorkerRef): Promise<void> {
    const { model, thinking, timeoutMs } = this.getPiConfig();

    if (!session.memorySessionId) {
      const syntheticMemorySessionId = `pi-${session.contentSessionId}-${Date.now()}`;
      session.memorySessionId = syntheticMemorySessionId;
      this.dbManager.getSessionStore().updateMemorySessionId(session.sessionDbId, syntheticMemorySessionId);
      logger.info('SESSION', `MEMORY_ID_GENERATED | sessionDbId=${session.sessionDbId} | provider=Pi`);
    }

    const mode = ModeManager.getInstance().getActiveMode();
    const initPrompt = session.lastPromptNumber === 1
      ? buildInitPrompt(session.project, session.contentSessionId, session.userPrompt, mode)
      : buildContinuationPrompt(session.userPrompt, session.lastPromptNumber, session.contentSessionId, mode);

    session.conversationHistory.push({ role: 'user', content: initPrompt });

    try {
      const initResponse = await this.queryPi(session.conversationHistory, model, thinking, timeoutMs, session.abortController);
      await this.handleResponse(initResponse, session, worker, null, undefined, model);
    } catch (error) {
      await this.handleSessionError(error, session);
      return;
    }

    let lastCwd: string | undefined;
    try {
      for await (const message of this.sessionManager.getMessageIterator(session.sessionDbId)) {
        lastCwd = await this.processOneMessage(session, message, lastCwd, model, thinking, timeoutMs, worker, mode);
      }
    } catch (error) {
      await this.handleSessionError(error, session);
      return;
    }

    const sessionDuration = Date.now() - session.startTime;
    logger.success('SDK', 'Pi agent completed', {
      sessionId: session.sessionDbId,
      duration: `${(sessionDuration / 1000).toFixed(1)}s`,
      historyLength: session.conversationHistory.length,
      model,
      thinking,
    });
  }

  private async processOneMessage(
    session: ActiveSession,
    message: PendingMessageWithId,
    lastCwd: string | undefined,
    model: string,
    thinking: string,
    timeoutMs: number,
    worker: WorkerRef | undefined,
    mode: ModeConfig,
  ): Promise<string | undefined> {
    session.pendingAgentId = message.agentId ?? null;
    session.pendingAgentType = message.agentType ?? null;
    if (message.cwd) lastCwd = message.cwd;
    const originalTimestamp = session.earliestPendingTimestamp;

    if (message.type === 'observation') {
      if (message.prompt_number !== undefined) session.lastPromptNumber = message.prompt_number;
      const obsPrompt = buildObservationPrompt({
        id: 0,
        tool_name: message.tool_name!,
        tool_input: JSON.stringify(message.tool_input),
        tool_output: JSON.stringify(message.tool_response),
        created_at_epoch: originalTimestamp ?? Date.now(),
        cwd: message.cwd,
      });
      session.conversationHistory.push({ role: 'user', content: obsPrompt });
      const response = await this.queryPi(session.conversationHistory, model, thinking, timeoutMs, session.abortController);
      await this.handleResponse(response, session, worker, originalTimestamp, lastCwd, model);
    } else if (message.type === 'summarize') {
      const summaryPrompt = buildSummaryPrompt({
        id: session.sessionDbId,
        memory_session_id: session.memorySessionId,
        project: session.project,
        user_prompt: session.userPrompt,
        last_assistant_message: message.last_assistant_message || '',
      }, mode);
      session.conversationHistory.push({ role: 'user', content: summaryPrompt });
      const response = await this.queryPi(session.conversationHistory, model, thinking, timeoutMs, session.abortController);
      await this.handleResponse(response, session, worker, originalTimestamp, lastCwd, model);
    }

    return lastCwd;
  }

  private async handleResponse(
    content: string,
    session: ActiveSession,
    worker: WorkerRef | undefined,
    originalTimestamp: number | null,
    lastCwd: string | undefined,
    model: string,
  ): Promise<void> {
    if (content) session.conversationHistory.push({ role: 'assistant', content });
    await processAgentResponse(content || '', session, this.dbManager, this.sessionManager, worker, 0, originalTimestamp, 'Pi', lastCwd, model);
  }

  private truncateHistory(history: ConversationMessage[]): ConversationMessage[] {
    const settings = SettingsDefaultsManager.loadFromFile(USER_SETTINGS_PATH);
    const maxMessages = Number.parseInt(settings.CLAUDE_MEM_PI_MAX_CONTEXT_MESSAGES || '', 10) || DEFAULT_MAX_CONTEXT_MESSAGES;
    const maxTokens = Number.parseInt(settings.CLAUDE_MEM_PI_MAX_TOKENS || '', 10) || DEFAULT_MAX_ESTIMATED_TOKENS;
    let truncated = history.slice(-maxMessages);
    while (truncated.length > 1) {
      const estimated = Math.ceil(truncated.map((m) => m.content).join('').length / CHARS_PER_TOKEN_ESTIMATE);
      if (estimated <= maxTokens) break;
      truncated = truncated.slice(1);
    }
    return truncated;
  }

  private async queryPi(
    history: ConversationMessage[],
    model: string,
    thinking: string,
    timeoutMs: number,
    abortController: AbortController,
  ): Promise<string> {
    const tempDir = mkdtempSync(join(tmpdir(), 'claude-mem-pi-provider-'));
    const systemPath = join(tempDir, 'system.md');
    const promptPath = join(tempDir, 'prompt.md');
    const stdoutPath = join(tempDir, 'stdout.txt');
    const stderrPath = join(tempDir, 'stderr.txt');
    const truncatedHistory = this.truncateHistory(history);
    writeFileSync(systemPath, buildPiSystemPrompt(), 'utf8');
    writeFileSync(promptPath, buildPiPrompt(truncatedHistory), 'utf8');
    writeFileSync(stdoutPath, '', 'utf8');
    writeFileSync(stderrPath, '', 'utf8');

    const args = [
      '--no-extensions',
      '--no-context-files',
      '--no-skills',
      '--no-tools',
      '--system-prompt', systemPath,
      '--model', model,
      '--thinking', thinking,
      '--mode', 'json',
      '-p', `@${promptPath}`,
    ];

    logger.debug('SDK', 'Starting Pi provider subprocess', {
      command: `pi ${args.map(shellQuote).join(' ')}`,
      promptPath,
      model,
      thinking,
      historyLength: history.length,
      sentHistoryLength: truncatedHistory.length,
    });

    const stdoutFd = openSync(stdoutPath, 'a');
    const stderrFd = openSync(stderrPath, 'a');

    return await new Promise<string>((resolve, reject) => {
      let settled = false;
      const child = spawn('pi', args, {
        cwd: process.cwd(),
        env: { ...process.env },
        stdio: ['ignore', stdoutFd, stderrFd],
      });

      const cleanup = () => {
        try { closeSync(stdoutFd); } catch { /* ignore */ }
        try { closeSync(stderrFd); } catch { /* ignore */ }
      };

      const readOutput = () => ({
        stdout: readFileSync(stdoutPath, 'utf8'),
        stderr: readFileSync(stderrPath, 'utf8'),
      });

      const onAbort = () => {
        if (settled) return;
        settled = true;
        child.kill('SIGTERM');
        cleanup();
        reject(new ClassifiedProviderError('Pi provider aborted', { kind: 'transient', cause: new Error('aborted') }));
      };
      abortController.signal.addEventListener('abort', onAbort, { once: true });

      const timeout = setTimeout(() => {
        if (settled) return;
        settled = true;
        child.kill('SIGTERM');
        abortController.signal.removeEventListener('abort', onAbort);
        const { stderr } = readOutput();
        cleanup();
        reject(new ClassifiedProviderError(`Pi provider timed out after ${timeoutMs}ms${stderr ? `: ${stderr.slice(-1000)}` : ''}`, { kind: 'rate_limit', cause: new Error('timeout') }));
      }, timeoutMs);

      child.on('error', (error) => {
        if (settled) return;
        settled = true;
        clearTimeout(timeout);
        abortController.signal.removeEventListener('abort', onAbort);
        cleanup();
        reject(new ClassifiedProviderError(`Pi provider spawn failed: ${error.message}`, { kind: 'transient', cause: error }));
      });

      child.on('exit', (code) => {
        if (settled) return;
        settled = true;
        clearTimeout(timeout);
        abortController.signal.removeEventListener('abort', onAbort);
        const { stdout, stderr } = readOutput();
        cleanup();
        if (code !== 0) {
          const lower = `${stderr}\n${stdout}`.toLowerCase();
          const kind = lower.includes('quota') || lower.includes('context') || lower.includes('rate limit') ? 'quota_exhausted' : 'transient';
          reject(new ClassifiedProviderError(`Pi provider exited ${code ?? 'unknown'}: ${(stderr || stdout).slice(-2000)}`, { kind, cause: new Error(stderr || stdout) }));
          return;
        }
        const text = extractAssistantTextFromJsonEvents(stdout);
        resolve(text);
      });
    });
  }

  private async handleSessionError(error: unknown, session: ActiveSession): Promise<never> {
    if (isAbortError(error)) {
      logger.warn('SDK', 'Pi agent aborted', { sessionId: session.sessionDbId });
      throw error;
    }
    logger.failure('SDK', 'Pi agent error', { sessionDbId: session.sessionDbId }, error instanceof Error ? error : new Error(String(error)));
    throw error;
  }

  private getPiConfig(): { model: string; thinking: string; timeoutMs: number } {
    const settings = SettingsDefaultsManager.loadFromFile(USER_SETTINGS_PATH);
    return {
      model: settings.CLAUDE_MEM_PI_MODEL || settings.CLAUDE_MEM_MODEL || 'openai-codex/gpt-5.4-mini',
      thinking: settings.CLAUDE_MEM_PI_THINKING || 'minimal',
      timeoutMs: Number.parseInt(settings.CLAUDE_MEM_PI_TIMEOUT_MS || '120000', 10) || DEFAULT_TIMEOUT_MS,
    };
  }
}

export function isPiSelected(): boolean {
  const settings = SettingsDefaultsManager.loadFromFile(USER_SETTINGS_PATH);
  return settings.CLAUDE_MEM_PROVIDER === 'pi';
}

export function isPiAvailable(): boolean {
  return true;
}

export function classifyPiError(error: unknown): ClassifiedProviderError {
  if (error instanceof ClassifiedProviderError) return error;
  return new ClassifiedProviderError(error instanceof Error ? error.message : String(error), {
    kind: 'transient',
    cause: error,
  });
}
