import { buildContinuationPrompt, buildInitPrompt, buildObservationPrompt, buildSummaryPrompt } from '../../sdk/prompts.js';
import { parseAgentXml } from '../../sdk/parser.js';
import { SettingsDefaultsManager } from '../../shared/SettingsDefaultsManager.js';
import { USER_SETTINGS_PATH } from '../../shared/paths.js';
import { logger } from '../../utils/logger.js';
import { ModeManager } from '../domain/ModeManager.js';
import type { ModeConfig } from '../domain/types.js';
import type { ActiveSession, ConversationMessage, PendingMessageWithId } from '../worker-types.js';
import { DatabaseManager } from './DatabaseManager.js';
import { SessionManager } from './SessionManager.js';
import { isAbortError, processAgentResponse, type WorkerRef } from './agents/index.js';
import { ClassifiedProviderError } from './provider-errors.js';
import { globalCallerChain, type ResponseValidator } from './llm/index.js';

const validatePiOutput: ResponseValidator = (text: string) => {
  if (!text.trim()) return { valid: true };
  const parsed = parseAgentXml(text);
  if (parsed.valid) return { valid: true };
  return {
    valid: false,
    feedback: 'Response must be either one or more <observation>...</observation> blocks OR a single <summary>...</summary> block (matching the schema in the system prompt). No prose, no markdown code fences, no commentary outside the XML. If there is genuinely nothing durable to record, return an empty response instead — but never plain text.',
  };
};

const DEFAULT_TIMEOUT_MS = 120_000;
const DEFAULT_MAX_CONTEXT_MESSAGES = 20;
const DEFAULT_MAX_ESTIMATED_TOKENS = 100_000;
const CHARS_PER_TOKEN_ESTIMATE = 4;

function buildPiPrompt(history: ConversationMessage[]): string {
  return history
    .map((message) => `## ${message.role}\n${message.content}`)
    .join('\n\n---\n\n');
}

function buildPiSystemPrompt(): string {
  return `You are claude-mem's background fact extraction agent.

You receive synthetic prompts generated by claude-mem for session init, tool observations, and session summaries. Follow those prompts exactly and produce the structured memory/summary response requested by the prompt.

Critical output rules:
- Do not use tools.
- Do not ask questions.
- Return only the XML/structured content requested by the prompt; no markdown fence, no prose preface, no commentary.
- Never output template placeholders or bracketed schema examples as facts.
- Observation type values must be one of: bugfix, feature, refactor, change, discovery, decision, security_alert, security_note.
- If the observed input has no durable fact worth storing, return the prompt's explicit empty/no-op format if one is provided; otherwise return an empty response.`;
}

export class PiProvider {
  constructor(
    private dbManager: DatabaseManager,
    private sessionManager: SessionManager,
  ) {}

  async startSession(session: ActiveSession, worker?: WorkerRef): Promise<void> {
    const { timeoutMs } = this.getPiConfig();

    if (!session.memorySessionId) {
      const syntheticMemorySessionId = `pi-${session.contentSessionId}-${Date.now()}`;
      session.memorySessionId = syntheticMemorySessionId;
      this.dbManager.getSessionStore().updateMemorySessionId(session.sessionDbId, syntheticMemorySessionId);
      logger.info('SESSION', `MEMORY_ID_GENERATED | sessionDbId=${session.sessionDbId} | provider=Pi`);
    }

    const mode = ModeManager.getInstance().getActiveMode();
    const initPrompt = session.lastPromptNumber === 1
      ? buildInitPrompt(session.project, session.contentSessionId, session.userPrompt, mode)
      : buildContinuationPrompt(session.userPrompt, session.lastPromptNumber, session.contentSessionId, mode);

    session.conversationHistory.push({ role: 'user', content: initPrompt });

    try {
      const initResponse = await this.queryChain(session.conversationHistory, timeoutMs, session.abortController, 'pi-session-init');
      await this.handleResponse(initResponse.text, session, worker, null, undefined, initResponse.model);
    } catch (error) {
      await this.handleSessionError(error, session);
      return;
    }

    let lastCwd: string | undefined;
    try {
      for await (const message of this.sessionManager.getMessageIterator(session.sessionDbId)) {
        lastCwd = await this.processOneMessage(session, message, lastCwd, timeoutMs, worker, mode);
      }
    } catch (error) {
      await this.handleSessionError(error, session);
      return;
    }

    const sessionDuration = Date.now() - session.startTime;
    logger.success('SDK', 'Pi agent completed', {
      sessionId: session.sessionDbId,
      duration: `${(sessionDuration / 1000).toFixed(1)}s`,
      historyLength: session.conversationHistory.length,
    });
  }

  private async processOneMessage(
    session: ActiveSession,
    message: PendingMessageWithId,
    lastCwd: string | undefined,
    timeoutMs: number,
    worker: WorkerRef | undefined,
    mode: ModeConfig,
  ): Promise<string | undefined> {
    session.pendingAgentId = message.agentId ?? null;
    session.pendingAgentType = message.agentType ?? null;
    if (message.cwd) lastCwd = message.cwd;
    const originalTimestamp = session.earliestPendingTimestamp;

    if (message.type === 'observation') {
      if (message.prompt_number !== undefined) session.lastPromptNumber = message.prompt_number;
      const obsPrompt = buildObservationPrompt({
        id: 0,
        tool_name: message.tool_name!,
        tool_input: JSON.stringify(message.tool_input),
        tool_output: JSON.stringify(message.tool_response),
        created_at_epoch: originalTimestamp ?? Date.now(),
        cwd: message.cwd,
      });
      session.conversationHistory.push({ role: 'user', content: obsPrompt });
      const response = await this.queryChain(session.conversationHistory, timeoutMs, session.abortController, 'pi-observation');
      await this.handleResponse(response.text, session, worker, originalTimestamp, lastCwd, response.model);
    } else if (message.type === 'summarize') {
      const summaryPrompt = buildSummaryPrompt({
        id: session.sessionDbId,
        memory_session_id: session.memorySessionId,
        project: session.project,
        user_prompt: session.userPrompt,
        last_assistant_message: message.last_assistant_message || '',
      }, mode);
      session.conversationHistory.push({ role: 'user', content: summaryPrompt });
      const response = await this.queryChain(session.conversationHistory, timeoutMs, session.abortController, 'pi-summary');
      await this.handleResponse(response.text, session, worker, originalTimestamp, lastCwd, response.model);
    }

    return lastCwd;
  }

  private async handleResponse(
    content: string,
    session: ActiveSession,
    worker: WorkerRef | undefined,
    originalTimestamp: number | null,
    lastCwd: string | undefined,
    model: string,
  ): Promise<void> {
    if (content) session.conversationHistory.push({ role: 'assistant', content });
    await processAgentResponse(content || '', session, this.dbManager, this.sessionManager, worker, 0, originalTimestamp, 'Pi', lastCwd, model);
  }

  private truncateHistory(history: ConversationMessage[]): ConversationMessage[] {
    const settings = SettingsDefaultsManager.loadFromFile(USER_SETTINGS_PATH);
    const maxMessages = Number.parseInt(settings.CLAUDE_MEM_PI_MAX_CONTEXT_MESSAGES || '', 10) || DEFAULT_MAX_CONTEXT_MESSAGES;
    const maxTokens = Number.parseInt(settings.CLAUDE_MEM_PI_MAX_TOKENS || '', 10) || DEFAULT_MAX_ESTIMATED_TOKENS;
    let truncated = history.slice(-maxMessages);
    while (truncated.length > 1) {
      const estimated = Math.ceil(truncated.map((m) => m.content).join('').length / CHARS_PER_TOKEN_ESTIMATE);
      if (estimated <= maxTokens) break;
      truncated = truncated.slice(1);
    }
    while (truncated.length > 1 && truncated[0]?.role !== 'user') {
      truncated = truncated.slice(1);
    }
    return truncated;
  }

  private async queryChain(
    history: ConversationMessage[],
    timeoutMs: number,
    abortController: AbortController,
    agentTag: string,
  ): Promise<{ text: string; model: string }> {
    const truncatedHistory = this.truncateHistory(history);
    const result = await globalCallerChain.call({
      systemPrompt: buildPiSystemPrompt(),
      userPrompt: buildPiPrompt(truncatedHistory),
      mode: 'json',
      timeoutMs,
      abortSignal: abortController.signal,
      agentTag,
      validate: validatePiOutput,
    });
    logger.debug('SDK', 'CallerChain returned response', {
      provider: result.provider,
      model: result.model,
      agentTag,
      historyLength: history.length,
      sentHistoryLength: truncatedHistory.length,
    });
    return { text: result.text, model: result.model };
  }

  private async handleSessionError(error: unknown, session: ActiveSession): Promise<never> {
    if (isAbortError(error)) {
      logger.warn('SDK', 'Pi agent aborted', { sessionId: session.sessionDbId });
      throw error;
    }
    logger.failure('SDK', 'Pi agent error', { sessionDbId: session.sessionDbId }, error instanceof Error ? error : new Error(String(error)));
    throw error;
  }

  private getPiConfig(): { timeoutMs: number } {
    const settings = SettingsDefaultsManager.loadFromFile(USER_SETTINGS_PATH);
    return {
      timeoutMs: Number.parseInt(settings.CLAUDE_MEM_PI_TIMEOUT_MS || '120000', 10) || DEFAULT_TIMEOUT_MS,
    };
  }
}

export function isPiSelected(): boolean {
  const settings = SettingsDefaultsManager.loadFromFile(USER_SETTINGS_PATH);
  return settings.CLAUDE_MEM_PROVIDER === 'pi';
}

export function isPiAvailable(): boolean {
  return true;
}

export function classifyPiError(error: unknown): ClassifiedProviderError {
  if (error instanceof ClassifiedProviderError) return error;
  return new ClassifiedProviderError(error instanceof Error ? error.message : String(error), {
    kind: 'transient',
    cause: error,
  });
}
